enum {
    SOME=1, ALL, VALUE, MIN, MAX, EXACTLY, THAT, NOT, AND, OR, ONLY,
    CLASS, EQUIVALENTTO, INDIVIDUALS, SUBCLASSOF, DISJOINTCLASSES,

    CLASS_ID, PROP_ID, INDIVIDUAL_ID, DATA_TYPE, CARDINALITY,

    PARENTHESES, BRACKETS, BRACES, RELOP, COMMA, 
    
    ENDL
};